### ISSUE TITLE
new clone today has error in postCreateCommand

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/ai-rag-chat-evaluator#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Tested on both mac and win on new/fresh clone

Open in dev container. 

### Any log messages given by the failure
>

```
[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
An error has occurred: FatalError: git failed. Is it installed, and are you in a
 Git repository directory?
Check the log at /home/vscode/.cache/pre-commit/pre-commit.log
[522193 ms] postCreateCommand failed with exit code 1. Skipping any further user-provided commands.
Done. Press any key to close the terminal.
```

### Expected/desired behavior
> No errors at end of container startup

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
Interesting. I wonder now if its not a git issue but some sort of pre-commit issue. I'll just delete it from the postCreateCommand and make a CONTRIBUTING.md.
