### ISSUE TITLE
Dev Container post-create-command fails b/c GIT isn't installed

### ISSUE THREAD

**Issue by diberry** [Azure-Samples/ai-rag-chat-evaluator#2]
![image](https://github.com/Azure-Samples/ai-rag-chat-evaluator/assets/41597107/f776c846-38c9-481b-bc3f-c57d25273175)

Container does open.

**Comment by pamelafox** [comment]
Ah thats the second time I've gotten a report like this (but on a different repo). I'll ask if something happened with dev containers recently. You can delete pre-commit install from the postCreateCommand for now.

**Comment by diberry** [comment]
I wound up changing the dev container: 

```
"features": 
   ...
   "ghcr.io/devcontainers/features/git:1": {},
}
```

And will change the postCreateCommand to: 

```
    "postCreateCommand": "pip install -r requirements-dev.txt"
```
   
```

**Comment by pamelafox** [comment]
You could also try this fix:

[ -d .git ] && pre-commit install

That's what I've added to devcontainer.json

I haven't heard back from dev containers team on what changed to cause the errors.

**Comment by pamelafox** [comment]
What OS were you on when this happened?
