### ISSUE TITLE
Missing option '--numquestions'

### ISSUE THREAD

**Issue by KorbinianBraun4ntt** [Azure-Samples/ai-rag-chat-evaluator#37]
### This issue is for a: 
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run evaluation on all test data: python3 -m scripts evaluate --config=example_config.json

### Any log messages given by the failure
>vscode ➜ /workspaces/ai-rag-chat-evaluator (main) $ python3 -m scripts evaluate --config=example_config.json
Usage: python -m scripts evaluate [OPTIONS]
Try 'python -m scripts evaluate --help' for help.
 Error -->  Missing option '--numquestions'.                                                                                                                                                                                  

### Expected/desired behavior
> No Error: Should perform evaluation on all records provided in the qa.jsonl !

### OS and Version?
> Windows 10 

### Mention any other details that might be useful

> Evaluation works if the number of questions is provided '--numquestions='

**Comment by sofyan-ajridi-ey** [comment]
Can confirm, have the same issue on my end

**Comment by pamelafox** [comment]
Thanks so much for the report! I've merged a fix in https://github.com/Azure-Samples/ai-rag-chat-evaluator/pull/39

**Comment by KorbinianBraun4ntt** [comment]
Thank you very much for quick fix as always. 😊👍
