### ISSUE TITLE
yaml file does not exist

### ISSUE THREAD

**Issue by Niharika6442** [Azure-Samples/ai-rag-chat-evaluator#47]
I've taken the latest pull and facing this error: **mlflow.exceptions.MissingConfigException: Yaml file '..\mlruns\0\meta.yaml' does not exist.**

I tried to add meta.yaml file from old pull run and everything worked fine. Looks like something is missing in the latest code w.r.t this file.

**Comment by pamelafox** [comment]
Hm, I don't check that mlruns folder into the repo, and I often delete that mlruns folder entirely. Can you delete the whole mlruns folder and see if you still see an error?

**Comment by Niharika6442** [comment]
Looks like its resolved now after deleting the entire folder
