### ISSUE TITLE
Where to give input data to generate ground truth samples from?

### ISSUE THREAD

**Issue by Niharika6442** [Azure-Samples/ai-rag-chat-evaluator#5]
I'm trying to generate ground truth examples, where are we providing the data here?

**Comment by pamelafox** [comment]
It's set up to pull documents from an Azure AI Search index, but I failed to document the environment variables. Will do now!

**Comment by pamelafox** [comment]
Here you go:
https://github.com/Azure-Samples/ai-rag-chat-evaluator?tab=readme-ov-file#running-the-generator-script

Let me know if you have follow-up questions!
