### ISSUE TITLE
Incompatible Python Version 3.11, 3.12

### ISSUE THREAD

**Issue by singloudly90** [Azure-Samples/ai-rag-chat-evaluator#56]
> Please provide us with the following information:
> what version of python should be using for this repos? because it failed on installing the modules via python 3.11 and 3.12... for this 

pip install azure-ai-generative[evaluate]==1.0.0b7

or anything that i could missed out during the step?

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run with python 3.11 and python 3.12 with this pip install azure-ai-generative[evaluate]==1.0.0b7

### Any log messages given by the failure
>  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for rtoml
Successfully built google-search-results
Failed to build rtoml
ERROR: Could not build wheels for rtoml, which is required to install pyproject.toml-based projects

### Expected/desired behavior
> build successfully

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> 

### Mention any other details that might be useful
I able to run it with 
pip install --upgrade pip setuptools wheel
pip install --only-binary :all: rtoml
pip install azure-ai-generative
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

Thank you!

**Comment by pamelafox** [comment]
I haven't been able to replicate an install issue in the CI, and I just added Mac and 3.12 to the matrix: https://github.com/Azure-Samples/ai-rag-chat-evaluator/pull/73

I'm going to close this issue, but feel free to comment if you figure out a difference between your environment and what I've tested. Thanks!
