### ISSUE TITLE
Evaluate script not working

### ISSUE THREAD

**Issue by FranciscoMMendes** [Azure-Samples/ai-rag-chat-evaluator#60]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>python -m scripts evaluate --config=example_config.json
15:26:09 (INFO) scripts: Running evaluation from config C:\Users\FranciscoMendes\OneDrive\OpenAI_POCs\SPMS_POC_OpenAI\ai-rag-chat-evaluator\example_config.json
15:26:09 (INFO) scripts: Replaced results_dir in config with timestamp
15:26:09 (INFO) scripts: Replaced prompt_template in config with contents of example_input/prompt_refined.txt
15:26:09 (INFO) scripts: Using Azure OpenAI Service with Azure Developer CLI Credential
15:26:09 (INFO) azure.identity._internal.decorators: AzureDeveloperCliCredential.get_token succeeded
15:26:09 (INFO) scripts: Running evaluation using data from C:\Users\FranciscoMendes\OneDrive\OpenAI_POCs\SPMS_POC_OpenAI\ai-rag-chat-evaluator\example_input\qa.jsonl
15:26:09 (INFO) scripts: Sending a test question to the target to ensure it is running...
15:26:10 (ERROR) scripts: Failed to send a test question to the target due to error: 
Expecting value: line 1 column 1 (char 0)
15:26:10 (ERROR) scripts: Evaluation was terminated early due to an error ⬆

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
I am trying to run the evaluate script but it is not working. I have already managed to generate the json with the questions and answers correctly and changed the config.json with my required target but I keep getting the same error. The error seems to be related to the connection with the target endpoint.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by pamelafox** [comment]
It seems like it's getting an empty response from the endpoint. I'll try to add more debugging information to the logs to help. What endpoint did you specify in your config.json?

**Comment by FranciscoMMendes** [comment]
> It seems like it's getting an empty response from the endpoint. I'll try to add more debugging information to the logs to help. What endpoint did you specify in your config.json?

I'm using the Azure App Service URL as the endpoint in my config.json.

**Comment by pamelafox** [comment]
@FranciscoMMendes Did you put /chat at the end of that URL? And if you did, do you have authentication required for that URL?

**Comment by pamelafox** [comment]
I have added additional debugging to the evaluate call, so I'm going to close the issue. Please comment or open a new issue if further help is needed. Thanks!
